=pod

=head1 NAME

Dist::Zilla::Plugin::LocalBrew

=head1 VERSION

version 0.02

=head1 SYNOPSIS

This module is deprecated; please use L<Dist::Zilla::Plugin::Test::LocalBrew>
instead.

=head1 AUTHOR

Rob Hoelz <rob@hoelz.ro>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2011 by Rob Hoelz.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=head1 BUGS

Please report any bugs or feature requests on the bugtracker website
https://github.com/hoelzro/dist-zilla-plugin-localbrew/issues

When submitting a bug or request, please include a test-file or a
patch to an existing test-file that illustrates the bug or desired
feature.

